
//searches for all IDs to enable random image picking
query Overview {
  projectCategoryPages {
    slug
    id
    locale
    categoryTitle
    projects {
      ... on Project {
        id
        images {
          id
        }
      }
    }
  }
}
